# DATA
data_link: "https://www.kaggle.com/api/v1/datasets/download/ronanpickell/b200c-lego-classification-dataset"
data_handle: "ronanpickell/b200c-lego-classification-dataset"
data_name: b200c-lego-classification-dataset
data_dir: /data

# MODELS
model_path: /models

# RESULTS
results_path: /results

# API KEYS
rebrickable_api: "INSERT API KEY HERE" # Personal API key from "rebrickable.com" is needed.
kaggle_username: "YOUR KAGGLE USERNAME" # Instructions on how to get in "/src/data/download.py".
kaggle_api: "INSERT API KEY HERE" # Instructions on how to get in "/src/data/download.py".
