# DATA
data_path: data/

# CLASSIFICATION DATASETS
b200c_dataset_url: https://www.kaggle.com/datasets/ronanpickell/b200c-lego-classification-dataset
b200c_dataset_handle: ronanpickell/b200c-lego-classification-dataset
b200c_dataset_name: b200c-lego-classification-dataset

class_scraper_dataset0_url: https://mostwiedzy.pl/en/open-research-data/lego-bricks-for-training-classification-network,202309140842198941751-0
class_scraper_dataset0_download: https://mostwiedzy.pl/en/open-research-data/lego-bricks-for-training-classification-network,202309140842198941751-0/download
class_scraper_dataset0_name: synthetic_and_real_mix_dataset

class_scraper_dataset1_url: https://mostwiedzy.pl/en/open-research-data/images-of-lego-bricks,202309140837142278781-0
class_scraper_dataset1_download: https://mostwiedzy.pl/en/open-research-data/images-of-lego-bricks,202309140837142278781-0/download
class_scraper_dataset1_name: real_image_dataset

# OBJECT DETECTION DATASETS
b200_dataset_url: https://www.kaggle.com/datasets/ronanpickell/b100-lego-detection-dataset
b200_dataset_handle: ronanpickell/b100-lego-detection-dataset
b200_dataset_name: b200-lego-detection-dataset

# MODELS
model_path: models/

# CHECKPOINTS
temp_checkpoint_path: temp_checkpoints/

# RESULTS
results_path: results/

# LOGGING
logging_path: logs/
logging_level: debug

# API KEYS
rebrickable_api_key: INSERT API KEY HERE # Personal API key from "rebrickable.com" is needed.
kaggle_username: YOUR KAGGLE USERNAME # Instructions on how to get in "/src/data/download.py".
kaggle_api_key: INSERT API KEY HERE # Instructions on how to get in "/src/data/download.py".
