# DATA 
datalink: "https://www.kaggle.com/api/v1/datasets/download/ronanpickell/b200c-lego-classification-dataset"
datahandle: "ronanpickell/b200c-lego-classification-dataset"
dataname: b200c-lego-classification-dataset
datadirectory: data/

# MODELS
modelpath: models/model.pkl

# RESULTS
resultsrawpath: results/results_raw.pkl
resultsevaluatedpath: results/results_evaluated.pkl

# VISUALIZATION
figuredirectory: reports/figures/

# API KEYS
rebrickableapi: "insert API key here" # Personal API key from "rebrickable.com" is needed.